blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogDeleteView, BlogDetailView,
                        BlogListView, BlogUpdateView)

app_name = BlogConfig.name

urlpatterns = [
    path("blog/", BlogListView.as_view(), name="blog_list"),
    path("blog/create", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/<int:pk>/update", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete", BlogDeleteView.as_view(), name="blog_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (CategoryListView, ContactTemplateView,
                           ProductCreateView, ProductDeleteView,
                           ProductDetailView, ProductsByCategoryView,
                           ProductsListView, ProductUpdateView,
                           UnpublishedProductView)

app_name = CatalogConfig.name

urlpatterns = [
    path("home/", ProductsListView.as_view(), name="home"),
    path(
        "product/<int:pk>/",
        cache_page(60)(ProductDetailView.as_view()),
        name="product_detail",
    ),
    path("product/new/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/edit/", ProductUpdateView.as_view(), name="product_edit"),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path(
        "product/unpublished_product_views/<int:product_id>/",
        UnpublishedProductView.as_view(),
        name="unpublished_product_views",
    ),
    path("contacts/", ContactTemplateView.as_view(), name="contacts"),
    path("category/", CategoryListView.as_view(), name="category_list"),
    path(
        "category/<int:pk>/",
        ProductsByCategoryView.as_view(),
        name="products_by_category",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="Заголовок")
    content = models.TextField(verbose_name="Содержимое")
    image = models.ImageField(
        upload_to="media/images", blank=True, null=True, verbose_name="Изображение"
    )
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    publication = models.BooleanField(default=True, verbose_name="публикация")
    number_views = models.PositiveIntegerField(
        verbose_name="Количество просмотров",
        help_text="Укажите количество просмотров",
        default=0,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from .models import Blog


class BlogListView(ListView):
    model = Blog
    template_name = "blog_list.html"
    context_object_name = "blog"

    def get_queryset(self):
        # Получаем только активные объекты
        return Blog.objects.filter(publication=True)


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = (
        "title",
        "content",
        "image",
    )
    template_name = "blog_form.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ("title", "content", "image")
    template_name = "blog_form.html"
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog_detail.html"
    context_object_name = "blog"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = "blog_confirm_delete.html"
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog_base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include 'blog_header.html' %}
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

</div>
{% block content %}
{% endblock %}
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
             Marketplay
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog_confirm_delete.html
{% extends 'blog_base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text text-center">Вы уверенны?</p>
                    <div class="card-body">
                        <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
                        </form>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog_detail.html
{% extends 'blog_base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Категории</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title}}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ object.content}}</h2>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3"></ul>
                    <img src="{{ blog.image.url }}" class="img-fluid" style="height: 180px;">
                </div>
                <div class="btn-group">
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog_form.html
{% extends 'blog_base.html' %}
{% block content %}
<div class="container">
    <div class="row ">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {%  endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog_header.html
<header>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Магазин</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="/contact/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Блог</a>
    </nav>
</div>
</header>

blog/templates/blog_list.html
{% extends 'blog_base.html' %}
{% block content %}
   <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">БЛОГ МАГАЗИНА</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ blog.title}}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">Описание</h2>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li class="text-center">{{ blog.content|truncatechars:100}}</li>
                    </ul>
                    <img src="{{ blog.image.url }}" class="img-fluid" style="height: 180px;">
                    <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Перейти</a>
                        <a class="btn btn-primary" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                        <a class="btn btn-danger" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                    </div>
                    <h4 class="card-title pricing-card-title">Количество просмотров: {{ blog.number_views }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
<div class="row text-center">
    <div class="col-12 ">
                <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Создать новый блог</a>
    </div>
</div>
{% endblock %}