blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogDeleteView, BlogDetailView,
                        BlogListView, BlogUpdateView)

app_name = BlogConfig.name

urlpatterns = [
    path("blog/", BlogListView.as_view(), name="blog_list"),
    path("blog/create", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/<int:pk>/update", BlogUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete", BlogDeleteView.as_view(), name="blog_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (CategoryListView, ContactTemplateView,
                           ProductCreateView, ProductDeleteView,
                           ProductDetailView, ProductsByCategoryView,
                           ProductsListView, ProductUpdateView,
                           UnpublishedProductView)

app_name = CatalogConfig.name

urlpatterns = [
    path("home/", ProductsListView.as_view(), name="home"),
    path(
        "product/<int:pk>/",
        cache_page(60)(ProductDetailView.as_view()),
        name="product_detail",
    ),
    path("product/new/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/edit/", ProductUpdateView.as_view(), name="product_edit"),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path(
        "product/unpublished_product_views/<int:product_id>/",
        UnpublishedProductView.as_view(),
        name="unpublished_product_views",
    ),
    path("contacts/", ContactTemplateView.as_view(), name="contacts"),
    path("category/", CategoryListView.as_view(), name="category_list"),
    path(
        "category/<int:pk>/",
        ProductsByCategoryView.as_view(),
        name="products_by_category",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .apps import UsersConfig
from .views import RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="catalog:home"), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

catalog/models.py
from django.db import models

from config import settings
from users.models import CustomUser


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Категория",
        help_text="Введите наименование категории",
    )  # наименование,
    description = models.TextField(
        verbose_name="Описание", blank=True, null=True
    )  # описание,

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    names = models.CharField(
        max_length=100, verbose_name="Наименование"
    )  # наименование,
    description = models.TextField(
        verbose_name="Описание", blank=True, null=True
    )  # описание,
    image = models.ImageField(
        upload_to="media/images", blank=True, null=True, verbose_name="Изображение"
    )  # изображение,
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        related_name="products",
    )  # категория,
    price = models.IntegerField(verbose_name="Цена")  # цена за покупку,
    created_at = models.DateField(
        auto_now_add=True, verbose_name="Дата создания"
    )  # дата создания,
    updated_at = models.DateField(
        auto_now_add=True, verbose_name="Дата последнего изменения"
    )  # дата последнего изменения.
    publication = models.BooleanField(default=False, verbose_name="Статус публикации")
    owner = models.ForeignKey(
        CustomUser,
        verbose_name="имя владельца",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["names", "category"]
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
            ("remove_any_product", "Remove any product"),
        ]

    def __str__(self):
        return self.names

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models import Product

forbidden = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["names", "description", "image", "category", "price", "publication"]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields["names"].widget.attrs.update(
            {
                "class": "form-control",  # Добавление CSS-класса для стилизации поля
                "placeholder": "Введите названия продукта",  # Текст подсказки внутри поля
            }
        )

        self.fields["description"].widget.attrs.update(
            {
                "class": "form-control",  # Добавление CSS-класса для стилизации поля
                "placeholder": "Описание продукта",  # Текст подсказки внутри поля
            }
        )

        self.fields["category"].widget.attrs.update(
            {
                "class": "form-control",  # Добавление CSS-класса для стилизации поля
            }
        )

        self.fields["price"].widget.attrs.update(
            {
                "class": "form-control",  # Добавление CSS-класса для стилизации поля
                "placeholder": "Укажите цену",  # Указание типа поля как даты
            }
        )

    def clean(self):
        names = self.cleaned_data.get("names")
        description = self.cleaned_data.get("description")
        for word in forbidden:
            if word in names.lower() or word in description.lower():
                raise ValidationError(
                    "Название и описание не должны содержать запрещенные слова."
                )
        return self.cleaned_data

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Цена продукта не может быть отрицательной.")
        return price

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from catalog.forms import ProductForm
from catalog.models import Category, Product
from catalog.servise import get_products_by_category, get_products_from_cache


def my_view(request):
    # Попытка получить данные из кеша
    data = cache.get("my_key")

    # Если данные не найдены в кеше, выполняем вычисления и сохраняем результат в кеш
    if not data:
        data = "some expensive computation"
        cache.set("my_key", data, 60 * 15)  # Кешируем данные на 15 минут

    # Возвращаем ответ с данными
    return HttpResponse(data)


class UnpublishedProductView(LoginRequiredMixin, View):
    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)

        if not request.user.has_perm("catalog.can_unpublish_product"):
            return HttpResponseForbidden("У вас нет прав отмены публикации.")

        product.publication = False
        product.save()

        return redirect("catalog:product_detail", pk=product_id)


class ProductsListView(ListView):
    model = Product
    template_name = "catalog/home.html"
    context_object_name = "products"

    def get_queryset(self):
        return get_products_from_cache()


class ProductsByCategoryView(ListView):
    model = Category
    template_name = "catalog/home.html"
    context_object_name = "products_by_category"

    def get_queryset(self):
        category_id = self.kwargs.get("pk")
        return get_products_by_category(category_id=category_id)


class CategoryListView(ListView):
    model = Category


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_create.html"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:home")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            return self.object
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product_confirm_delete.html"
    success_url = reverse_lazy("catalog:home")

    def get_object(self, queryset=None):
        product = super().get_object(queryset)
        user = self.request.user

        if product.owner != user and not user.has_perm("catalog.product_delete"):
            raise PermissionDenied("Вы не можете удалять этот продукт.")

        return product


class ContactTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Marketplay{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

</head>
<body>
{% include 'catalog/header.html' %}
<div class="container">
    {% block content %}{% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Marketplay
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="row justify-content-center">
        <div class="col-6"></div>
        <div class="col-2">
            <h3>Категории</h3>
        </div>
        <div class="col-4"></div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for category in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h3 class="card-text">{{ category.name }}</h3>
                        <p class="card-text">{{ category.description|truncatechars:100 }}</p>
                        {% if user.is_authenticated %}
                        <div class="btn-group mt-2">
                            <a class="btn btn-primary"
                               href="{% url 'catalog:products_by_category' category.pk %}" role="button">Список
                                товаров</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/header.html
<header>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Marketplay</h5>
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:category_list' %}">Категории товаров</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Все товары</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить товар</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        </nav>
        <div class="col-md text-end">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'users:logout' %}" class="p-2 btn btn-outline-primary">
                {% csrf_token %}
                <button type="submit" class="btn btn-link nav-link">Выйти
                </button>
            </form>
            {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}

        </div>
    </div>

</header>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}


{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Продукты</h1>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for product in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ product.names }}</h4>
            </div>
            <div class="card-body">
                <img src="{{ product.image.url }}" class="img-fluid" style="height: 180px;">
                <h1 class="card-title pricing-card-title">{{ product.price }} руб. за кг.</h1>
                <p>Описание: {{ product.description|truncatechars:100 }}</p>
                <a class="btn btn-primary  " href="{% url 'catalog:product_detail' product.pk %}" role="button">Купить</a>
                 {% if product.owner == user %}
                <a class="btn btn-primary  " href="{% url 'catalog:product_edit' product.pk %}" role="button">Редоктировать</a>
                {% endif %}
                {% if product.owner == user or 'catalog.product_delete' in perms %}
                <a class="btn btn-primary  " href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Удаление</h1>
</div>
<div class="row text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.names }}</h4>
            </div>
            <div class="card-body">
                <p>Вы уверены, что хотите удалить "{{ object.names }}"?</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Добавление товара</h1>
</div>
<div class="row text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.names }}</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Продукты</h1>
</div>
<div class="row text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.names }}</h4>
            </div>
            <div class="card-body">
                <img src="{{ product.image.url }}" class="w-30" alt="...">
                <h1 class="card-title pricing-card-title">{{ object.price }} руб. за кг.</h1>
                <h5>Описание: {{ object.description}}</h5>
                <div class="d-grid gap-2">
                    <button type="button" class="w-100 btn btn-lg btn-outline-primary">Купить</button>
                    <form method="post" action="{% url 'catalog:unpublished_product_views' product.id %}">
                        {% csrf_token %}
                        <button type="button" class="w-100 btn btn-lg btn-outline-secondary">Отмена публикации</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Редактирование</h1>
</div>
<div class="row text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.names }}</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}